### PR TITLE
feat: added endpoint and force_path_style config for the aws remote

### PR DESCRIPTION
**Pull request by Wicpar**
I would like to use this library with storj, this is the easiest way to allow compatibility. It would be posible to add the full SDK but it would be too much clutter as it is bindings over a go library.

### CODE REVIEW

**Comment by galeone** [comment]
Hi @Wicpar - thanks for this PR!

I just ran the CI and cargo fmt is failing (https://github.com/galeone/bacup/actions/runs/8308441086/job/22757505131?pr=25). Can you please format the code with cargo fmt?

Also, can you also bump the library version to `0.1.13` in `Cargo.toml `? That way, once this is merged (and I really want to), I can release a new version without adding another commit only for the bump.

**Comment by Wicpar** [comment]
done, i still don't understand why rustrover doesn't use cargo fmt by default...

**Comment by galeone** [comment]
Merged, thank you very much!
Releasing the new version in a couple of minutes

**Comment by Wicpar** [comment]
looks like it works :)
just had an issue where i had to sudo in the service file or it wouldn't connect to the docker daemon, maybe there is a better way ?

**Comment by galeone** [comment]
`sudo usermod -aG docker $USER`

maybe

**Pull request merged**
